# PURL configuration for http://purl.obolibrary.org/obo/obcs

idspace: OBCS
base_url: /obo/obcs

products:
- obcs.owl: https://raw.githubusercontent.com/obcs/obcs/master/obcs.owl
- obcs_uncertainty.owl: https://raw.githubusercontent.com/obcs/obcs/master/views/obcs_uncertainty.owl

term_browser: ontobee
example_terms:
- OBCS_0000001

entries:
- exact: /tracker
  replacement: https://github.com/obcs/obcs/issues

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/obcs/obcs/v
  
### Current Releases

- exact: /2023-12-08/obcs.owl
  replacement: https://raw.githubusercontent.com/obcs/obcs/v2023-12-08/obcs.owl
  
- exact: /2023-12-09/obcs_uncertainty.owl
  replacement: https://raw.githubusercontent.com/obcs/obcs/v2023-12-08/views/obcs_uncertainty.owl

### Dated OBCS Releases

- exact: /2018-02-22/obcs.owl
  replacement: https://raw.githubusercontent.com/obcs/obcs/master/release/20180222/obcs_merged_inferred.owl
  
- exact: /2017-04-29/obcs.owl
  replacement: https://raw.githubusercontent.com/obcs/obcs/master/release/20170429/obcs_merged_inferred.owl
  
- exact: /2016-06-04/obcs.owl
  replacement: https://raw.githubusercontent.com/obcs/obcs/master/release/20160604/obcs_merged_inferred.owl

- exact: /2015-11-18/obcs.owl
  replacement: https://raw.githubusercontent.com/obcs/obcs/master/release/20151118/obcs_merged_inferred.owl

- exact: /2015-04-17/obcs.owl
  replacement: https://raw.githubusercontent.com/obcs/obcs/master/release/20150417/obcs_merged_inferred.owl
